apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpacker-deployment
spec:
  selector:
    matchLabels:
      app: unpacker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unpacker
    spec:
      containers:
      - image: instance-1.europe-west1-b.c.agile-splicer-218512.internal:5000/divolte-unpacker
        name: unpacker