apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  ports:
  - port: 8888
    nodePort: 30001
  type: NodePort
  selector:
    app: notebook
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: notebook
spec:
  selector:
    matchLabels:
      app: notebook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - image: jupyter/all-spark-notebook
        name: notebook
        ports:
        - containerPort: 8888
          name: notebook