global:
  evaluation_interval: 5s
  external_labels: {monitor: test-course}
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
- honor_labels: true
  job_name: pushgateway
  static_configs:
  - targets: ['pushgateway:9091']
- job_name: telemetry
  static_configs:
  - labels: {t_host: 195.93.229.67}
    targets: ['telemetry:5000']
- job_name: navigation
  static_configs:
  - labels: {n_host: '195.93.229.66:4242'}
    targets: ['navigation:5000']
- job_name: processing
  static_configs:
  - labels: {p_job: 0}
    targets: ['processing:5000']
  - labels: {p_job: 1}
    targets: ['processing:5001']
